os:
    - linux
    - osx
    - windows
language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true
before_install:
     - sudo apt-get install libgtk-3-0 libgtk-3-dev
addons:
    apt:
        update: true

