os:
    - linux
    - osx
    - windows
language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true
addons:
    apt:
        update: true
        packages:
            - libgtk-3-0
            - libgtk-3-dev

